name: 'Link local gem'
description: 'Link a local gem into an application Gemfile'
inputs:
  application_dir:
    description: 'The directory where the application lives'
    required: true
    type: string
  local_gem_dir:
    description: 'The directory containing the gem to link'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: pwd
      name: "pwd application_dir"
      working-directory: ${{ inputs.application_dir }}
      shell: bash
    - run: ls -al
      name: "ls -al application_dir"
      working-directory: ${{ inputs.application_dir }}
      shell: bash

    - run: pwd
      name: "pwd local_gem_dir"
      working-directory: ${{ inputs.local_gem_dir }}
      shell: bash
    - run: ls -al
      name: "ls -al local_gem_dir"
      working-directory: ${{ inputs.local_gem_dir }}
      shell: bash

    - name: Link local repos
      working-directory: ${{ github.action_path }}
      run: ./link-gem.sh
      shell: bash
      env:
        APPLICATION_DIR: ${{ inputs.application_dir }}
        LOCAL_GEM_DIR: ${{ inputs.local_gem_dir }}
        WORKSPACE: ${{ github.workspace }}

    - run: pwd
      working-directory: ${{ inputs.application_dir }}
      shell: bash
    - run: ls -al
      working-directory: ${{ inputs.application_dir }}
      shell: bash


